# Generated by Django 6.0.5 on 2026-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behandeling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Behandeling',
                'verbose_name_plural': 'Behandelingen',
                'db_table': 'behandelingen',
            },
        ),
        migrations.CreateModel(
            name='Zorgaanbieder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number_1', models.BigIntegerField(blank=True, null=True)),
                ('phone_number_2', models.BigIntegerField(blank=True, null=True)),
                ('phone_number_3', models.BigIntegerField(blank=True, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('behandelingen', models.ManyToManyField(blank=True, db_table='zorgaanbieder_behandelingen', to='api.behandeling')),
            ],
            options={
                'verbose_name': 'Zorgaanbieder',
                'verbose_name_plural': 'Zorgaanbieders',
                'db_table': 'zorgaanbieders',
            },
        ),
    ]
