# Generated by Django 6.0.5 on 2026-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Producten',
                'db_table': 'producten',
            },
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zorgaanbieder',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zorgaanbieder',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zorgaanbieder',
            name='phone_number_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='producten',
            field=models.ManyToManyField(blank=True, db_table='zorgaanbieder_producten', to='api.product'),
        ),
    ]
