# Generated by Django 6.0.5 on 2026-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_zorgaanbieder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zorgaanbieder',
            name='notes_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='notes_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
