# Generated by Django 6.0.5 on 2026-05-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_zorgaanbieder_notes_date_zorgaanbieder_notes_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='zorgaanbieder',
            name='regio_indeling',
            field=models.CharField(default='Lokaal', max_length=255),
            preserve_default=False,
        ),
    ]
