# Generated by Django 6.0.5 on 2026-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_zorgaanbieder_regio_indeling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zorgaanbieder',
            old_name='notes_date',
            new_name='notes_created_at',
        ),
        migrations.AlterField(
            model_name='zorgaanbieder',
            name='regio_indeling',
            field=models.CharField(choices=[('lokaal', 'Lokaal'), ('regionaal', 'Regionaal')], max_length=20),
        ),
    ]
