# Generated by Django 6.0.5 on 2026-06-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_notes_date_zorgaanbieder_notes_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Behandeling',
            new_name='Problematiek',
        ),
        migrations.AlterModelOptions(
            name='problematiek',
            options={'verbose_name': 'Problematiek', 'verbose_name_plural': 'Problematieken'},
        ),
        migrations.RemoveField(
            model_name='zorgaanbieder',
            name='behandelingen',
        ),
        migrations.RemoveField(
            model_name='zorgaanbieder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='zorgaanbieder',
            name='notes_created_at',
        ),
        migrations.RemoveField(
            model_name='zorgaanbieder',
            name='notes_owner',
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='problematieken',
            field=models.ManyToManyField(blank=True, db_table='zorgaanbieder_problematieken', to='api.problematiek'),
        ),
        migrations.AlterModelTable(
            name='problematiek',
            table='problematieken',
        ),
        migrations.CreateModel(
            name='Opmerking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.zorgaanbieder')),
            ],
            options={
                'verbose_name': 'Opmerking',
                'verbose_name_plural': 'Opmerkingen',
                'db_table': 'opmerkingen',
            },
        ),
    ]
