# Generated by Django 6.0.5 on 2026-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_behandeling_problematiek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zorgaanbieder',
            name='wachtrij_opmerking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
