# Generated by Django 6.0.5 on 2026-06-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_zorgaanbieder_wachtrij_opmerking'),
    ]

    operations = [
        migrations.AddField(
            model_name='zorgaanbieder',
            name='wachtrij_laatst_aangepast',
            field=models.DateField(blank=True, null=True),
        ),
    ]
